units:
  # Keycap
  krx: 16.5
  kry: 16.5
  p: 1.27
  po: 1.6
  # Keycap
  kx: krx + p
  ky: kry + p
  mr: 6.1
  sr: 1.6
points:
  zones:
    matrix:
      anchor:
        shift: [100, -100]
      key:
        padding: 1ky
        spread: 1kx
      columns:
        outer:
          key:
            column_net: P0
            mirror.column_net: P0_mirror
        pinky:
          key:
            splay: 0
            column_net: P1
            mirror.column_net: P1_mirror
        ring:
          key:
            stagger: 0.7ky
            column_net: P2
            mirror.column_net: P2_mirror
        middle:
          key:
            stagger: 0.5ky
            column_net: P3
            mirror.column_net: P3_mirror
        index:
          key:
            stagger: -0.2ky
            column_net: P4
            mirror.column_net: P4_mirror
        inner:
          key:
            column_net: P5
            mirror.column_net: P5_mirror
      rows:
        bottom:
          row_net: P9
          mirror.row_net: P9_mirror
        home:
          row_net: P8
          mirror.row_net: P8_mirror
        top:
          row_net: P7
          mirror.row_net: P7_mirror
    thumbs:
      key:
        padding: 1ky
        spread: 1kx
      anchor:
        ref: matrix_middle_bottom
        shift: [1kx, -1.2ky]
      columns:
        alpha:
          key:
            column_net: P3
            mirror.column_net: P3_mirror
        beta:
          key:
            column_net: P4
            mirror.column_net: P4_mirror
        gamma:
          key:
            column_net: P5
            mirror.column_net: P5_mirror
      rows:
        cluster:
          row_net: P6
          mirror.row_net: P6_mirror

  rotate: -0
  mirror: &mirror
    ref: thumbs_gamma_cluster
    distance: 1kx+2p+2
outlines:
  _keys:
    - what: rectangle
      where: true
      size: [krx, kry]
  _magnets:
    - what: circle
      radius: mr
      where:
        ref: thumbs_gamma_cluster
        shift: [0kx, 1.2ky]
    - what: circle
      radius: sr
      where:
        ref: thumbs_gamma_cluster
        shift: [0.25kx, 0.95ky]
    - what: circle
      radius: sr
      where:
        ref: thumbs_gamma_cluster
        shift: [-0.25kx, 0.95ky]
    - what: circle
      radius: sr
      where:
        ref: thumbs_gamma_cluster
        shift: [0.25kx, 1.45ky]
    - what: circle
      radius: sr
      where:
        ref: thumbs_gamma_cluster
        shift: [-0.25kx, 1.45ky]

    - what: circle
      radius: mr
      where:
        ref: thumbs_gamma_cluster
        shift: [0kx, 2.8ky]
    - what: circle
      radius: sr
      where:
        ref: thumbs_gamma_cluster
        shift: [0.25kx, 2.55ky]
    - what: circle
      radius: sr
      where:
        ref: thumbs_gamma_cluster
        shift: [-0.25kx, 2.55ky]
    - what: circle
      radius: sr
      where:
        ref: thumbs_gamma_cluster
        shift: [0.25kx, 3.05ky]
    - what: circle
      radius: sr
      where:
        ref: thumbs_gamma_cluster
        shift: [-0.25kx, 3.05ky]

  _magnets_mirror:
    - what: circle
      radius: mr
      where:
        ref: mirror_thumbs_gamma_cluster
        shift: [0kx, 1.2ky]
    - what: circle
      radius: sr
      where:
        ref: mirror_thumbs_gamma_cluster
        shift: [0.25kx, 0.95ky]
    - what: circle
      radius: sr
      where:
        ref: mirror_thumbs_gamma_cluster
        shift: [-0.25kx, 0.95ky]
    - what: circle
      radius: sr
      where:
        ref: mirror_thumbs_gamma_cluster
        shift: [0.25kx, 1.45ky]
    - what: circle
      radius: sr
      where:
        ref: mirror_thumbs_gamma_cluster
        shift: [-0.25kx, 1.45ky]

    - what: circle
      radius: mr
      where:
        ref: mirror_thumbs_gamma_cluster
        shift: [0kx, 2.8ky]
    - what: circle
      radius: sr
      where:
        ref: mirror_thumbs_gamma_cluster
        shift: [0.25kx, 2.55ky]
    - what: circle
      radius: sr
      where:
        ref: mirror_thumbs_gamma_cluster
        shift: [-0.25kx, 2.55ky]
    - what: circle
      radius: sr
      where:
        ref: mirror_thumbs_gamma_cluster
        shift: [0.25kx, 3.05ky]
    - what: circle
      radius: sr
      where:
        ref: mirror_thumbs_gamma_cluster
        shift: [-0.25kx, 3.05ky]
  _main:
    - what: polygon
      operation: stack
      points:
        - ref: matrix_outer_top
          shift: [-0.5kx-po, 1.7ky+2po]
        - ref: matrix_index_top
          shift: [-0.5kx+po, 0.7ky+2po]
        - ref: matrix_index_top
          shift: [-0.5kx+po, 0.5ky+po]
        - ref: matrix_inner_top
          shift: [1.25kx+po, 0.5ky+po]
        - ref: matrix_inner_top
          shift: [1.25kx+po, 0.7ky+2po]
        - ref: matrix_inner_top
          shift: [1.5kx+po, 0.7ky+2po]
        - ref: thumbs_gamma_cluster
          shift: [0.5kx+po, -0.5ky-2po]
        - ref: matrix_outer_bottom
          shift: [-0.5kx-po, -0.5ky-2po]
      fillet: sr
  _main_mirror:
    - what: polygon
      operation: stack
      points:
        - ref: mirror_matrix_outer_top
          shift: [-0.5kx-po, 1.7ky+2po]
        - ref: mirror_matrix_index_top
          shift: [-0.5kx+po, 0.7ky+2po]
        - ref: mirror_matrix_index_top
          shift: [-0.5kx+po, 0.5ky+po]
        - ref: mirror_matrix_inner_top
          shift: [1.25kx+po, 0.5ky+po]
        - ref: mirror_matrix_inner_top
          shift: [1.25kx+po, 0.7ky+2po]
        - ref: mirror_matrix_inner_top
          shift: [1.5kx+po, .7ky+2po]
        - ref: mirror_thumbs_gamma_cluster
          shift: [0.5kx+po, -0.5ky-2po]
        - ref: mirror_matrix_outer_bottom
          shift: [-0.5kx-po, -0.5ky-2po]
      fillet: sr
  board:
    - name: _main
    - operation: subtract
      name: _magnets

    - name: _main_mirror
    - operation: subtract
      name: _magnets_mirror
  combo:
    - name: board
    - operation: subtract
      name: _keys
pcbs:
  kbd:
    outlines:
      main:
        outline: board
    footprints:
      keys:
        what: kailh_x
        where: true
        params:
          from: "{{column_net}}"
          to: "{{colrow}}"
      diode:
        what: diode_sod323
        where: true
        params:
          from: "{{colrow}}"
          to: "{{row_net}}"
        adjust:
          shift: [0, 6]
          rotate: 180

      battery_power_mcu:
        what: thru_hole_pad
        params:
          net: BAT_VCC
        where:
          ref: matrix_pinky_top
          shift: [-0.2kx, 0.8ky]
      battery_power_mcu_mirror:
        what: thru_hole_pad
        params:
          net: BAT_VCC_MIRROR
        where:
          ref: mirror_matrix_pinky_top
          shift: [-0.2kx, 0.8ky]

      battery_power:
        what: thru_hole_pad
        params:
          net: BAT_VCC
        where:
          ref: matrix_middle_bottom
          shift: [-0.3kx, -1.4-0.9ky]
      battery_power_mirror:
        what: thru_hole_pad
        params:
          net: BAT_VCC_MIRROR
        where:
          ref: mirror_matrix_middle_bottom
          shift: [-0.3kx, -1.4-0.9ky]

      battery_power_gnd:
        what: thru_hole_pad
        params:
          net: GND
        where:
          ref: matrix_middle_bottom
          shift: [-0.3kx, 1.4-0.9ky]
      battery_power_gnd_mirror:
        what: thru_hole_pad
        params:
          net: GND_mirror
        where:
          ref: mirror_matrix_middle_bottom
          shift: [-0.3kx, 1.4-0.9ky]

      power_gnd:
        what: thru_hole_pad
        params:
          net: GND
        where:
          ref: thumbs_gamma_cluster
          shift: [0.5kx+p-3, 2ky-1.4]
      power_gnd_mirror:
        what: thru_hole_pad
        params:
          net: GND_mirror
        where:
          ref: mirror_thumbs_gamma_cluster
          shift: [0.5kx+p-3, 2ky-1.4]

      power_vcc:
        what: thru_hole_pad
        params:
          net: RAW
        where:
          ref: thumbs_gamma_cluster
          shift: [0.5kx+p-3, 2ky+1.4]
      power_vcc_mirror:
        what: thru_hole_pad
        params:
          net: RAW_mirror
        where:
          ref: mirror_thumbs_gamma_cluster
          shift: [0.5kx+p-3, 2ky+1.4]

      mcu:
        what: xiao_nrf52840
        where:
          ref: matrix_outer_top
          shift: [0.6kx, 0.8ky-1]
          rotate: 90
      mcu_mirror:
        what: xiao_nrf52840
        params:
          P0: P0_mirror
          P1: P1_mirror
          P2: P2_mirror
          P3: P3_mirror
          P4: P4_mirror
          P5: P5_mirror
          P6: P6_mirror
          P7: P7_mirror
          P8: P8_mirror
          P9: P9_mirror
          P10: P10_mirror
          VCC: VCC_mirror
          RAW: RAW_mirror
          GND: GND_mirror
        where:
          ref: mirror_matrix_outer_top
          shift: [0.6kx, 0.8ky-1+17.78]
          rotate: 90

      mount_hole_thumb:
        what: mounthole
        params:
          diameter: 3.2
        where:
          ref: thumbs_gamma_cluster
          shift: [0kx, 2ky]

      mount_hole_pinky:
        what: mounthole
        params:
          diameter: 3.2
        where:
          ref: matrix_pinky_top
          shift: [0kx, 1.25ky]

      mount_hole_middle:
        what: mounthole
        params:
          diameter: 3.2
        where:
          ref: matrix_middle_bottom
          shift: [0.2kx, -0.75ky]

      mount_hole_thumb_mirror:
        what: mounthole
        params:
          diameter: 3.2
        where:
          ref: mirror_thumbs_gamma_cluster
          shift: [0kx, 2ky]

      mount_hole_pinky_mirror:
        what: mounthole
        params:
          diameter: 3.2
        where:
          ref: mirror_matrix_pinky_top
          shift: [0kx, 1.25ky]

      mount_hole_middle_mirror:
        what: mounthole
        params:
          diameter: 3.2
        where:
          ref: mirror_matrix_middle_bottom
          shift: [0.2kx, -0.75ky]
