units:
  # Keycap
  krx: 16.5
  kry: 16.5
  p: 1.27
  po: 1.6
  # Keycap
  kx: krx + p
  ky: kry + p
  mr: 6.1
  sr: 1.6
points:
  zones:
    matrix:
      key:
        padding: 1ky
        spread: 1kx
      columns:
        outer:
        pinky:
          key:
            splay: 0
        ring:
          key:
            stagger: 0.7ky
        middle:
          key:
            stagger: 0.5ky
        index:
          key:
            stagger: -0.2ky
        inner:
      rows:
        bottom:
        home:
        top:
    thumbs:
      key:
        padding: 1ky
        spread: 1kx
      anchor:
        ref: matrix_middle_bottom
        shift: [1kx, -1.2ky]
      columns:
        alpha:
        beta:
        gamma:
      rows:
        cluster:

  rotate: -0
  mirror: &mirror
    ref: thumbs_gamma_cluster
    distance: 1.5kx
outlines:
  _keys:
    - what: rectangle
      where: true
      size: [krx, kry]

  _mount_holes:
    - what: circle
      radius: sr
      where:
        ref: thumbs_gamma_cluster
        shift: [0kx, 2ky]
    - what: circle
      radius: sr
      where:
        ref: matrix_pinky_top
        shift: [0kx, 1.25ky]
    - what: circle
      radius: sr
      where:
        ref: matrix_middle_bottom
        shift: [0kx, -0.75ky]

  _mount_holes_mirror:
    - what: circle
      radius: sr
      where:
        ref: mirror_thumbs_gamma_cluster
        shift: [0kx, 2ky]
    - what: circle
      radius: sr
      where:
        ref: mirror_matrix_pinky_top
        shift: [0.35kx, 0.65ky]
    - what: circle
      radius: sr
      where:
        ref: mirror_matrix_middle_bottom
        shift: [0kx, -0.75ky]

  _battery_cutout:
    - what: rectangle
      where:
        ref: matrix_outer_top
        shift: [-1.1, 1.3ky-1]
      size: [5.08, 12.7]

  _battery_cutout_mirror:
    - what: rectangle
      where:
        ref: mirror_matrix_outer_top
        shift: [-1.1, 1.3ky-1]
      size: [5.08, 12.7]

  _magnets:
    - what: circle
      radius: mr
      where:
        ref: thumbs_gamma_cluster
        shift: [0kx, 1.2ky]
    - what: circle
      radius: sr
      where:
        ref: thumbs_gamma_cluster
        shift: [0.25kx, 0.95ky]
    - what: circle
      radius: sr
      where:
        ref: thumbs_gamma_cluster
        shift: [-0.25kx, 0.95ky]
    - what: circle
      radius: sr
      where:
        ref: thumbs_gamma_cluster
        shift: [0.25kx, 1.45ky]
    - what: circle
      radius: sr
      where:
        ref: thumbs_gamma_cluster
        shift: [-0.25kx, 1.45ky]

    - what: circle
      radius: mr
      where:
        ref: thumbs_gamma_cluster
        shift: [0kx, 2.8ky]
    - what: circle
      radius: sr
      where:
        ref: thumbs_gamma_cluster
        shift: [0.25kx, 2.55ky]
    - what: circle
      radius: sr
      where:
        ref: thumbs_gamma_cluster
        shift: [-0.25kx, 2.55ky]
    - what: circle
      radius: sr
      where:
        ref: thumbs_gamma_cluster
        shift: [0.25kx, 3.05ky]
    - what: circle
      radius: sr
      where:
        ref: thumbs_gamma_cluster
        shift: [-0.25kx, 3.05ky]

  _magnets_mirror:
    - what: circle
      radius: mr
      where:
        ref: mirror_thumbs_gamma_cluster
        shift: [0kx, 1.2ky]
    - what: circle
      radius: sr
      where:
        ref: mirror_thumbs_gamma_cluster
        shift: [0.25kx, 0.95ky]
    - what: circle
      radius: sr
      where:
        ref: mirror_thumbs_gamma_cluster
        shift: [-0.25kx, 0.95ky]
    - what: circle
      radius: sr
      where:
        ref: mirror_thumbs_gamma_cluster
        shift: [0.25kx, 1.45ky]
    - what: circle
      radius: sr
      where:
        ref: mirror_thumbs_gamma_cluster
        shift: [-0.25kx, 1.45ky]

    - what: circle
      radius: mr
      where:
        ref: mirror_thumbs_gamma_cluster
        shift: [0kx, 2.8ky]
    - what: circle
      radius: sr
      where:
        ref: mirror_thumbs_gamma_cluster
        shift: [0.25kx, 2.55ky]
    - what: circle
      radius: sr
      where:
        ref: mirror_thumbs_gamma_cluster
        shift: [-0.25kx, 2.55ky]
    - what: circle
      radius: sr
      where:
        ref: mirror_thumbs_gamma_cluster
        shift: [0.25kx, 3.05ky]
    - what: circle
      radius: sr
      where:
        ref: mirror_thumbs_gamma_cluster
        shift: [-0.25kx, 3.05ky]
  _main:
    - what: polygon
      operation: stack
      points:
        - ref: matrix_outer_top
          shift: [-0.5kx-po, 1.7ky+2po]
        - ref: matrix_index_top
          shift: [-0.5kx+po, 0.7ky+2po]
        - ref: matrix_index_top
          shift: [-0.5kx+po, 0.5ky+po]
        - ref: matrix_inner_top
          shift: [1.25kx+po, 0.5ky+po]
        - ref: matrix_inner_top
          shift: [1.25kx+po, 0.7ky+2po]
        - ref: matrix_inner_top
          shift: [1.5kx+po, 0.7ky+2po]
        - ref: thumbs_gamma_cluster
          shift: [0.5kx+po, -0.5ky-2po]
        - ref: matrix_outer_bottom
          shift: [-0.5kx-po, -0.5ky-2po]
      fillet: sr
  _main_mirror:
    - what: polygon
      operation: stack
      points:
        - ref: mirror_matrix_outer_top
          shift: [-0.5kx-po, 1.7ky+2po]
        - ref: mirror_matrix_index_top
          shift: [-0.5kx+po, 0.7ky+2po]
        - ref: mirror_matrix_index_top
          shift: [-0.5kx+po, 0.5ky+po]
        - ref: mirror_matrix_inner_top
          shift: [1.25kx+po, 0.5ky+po]
        - ref: mirror_matrix_inner_top
          shift: [1.25kx+po, 0.7ky+2po]
        - ref: mirror_matrix_inner_top
          shift: [1.5kx+po, .7ky+2po]
        - ref: mirror_thumbs_gamma_cluster
          shift: [0.5kx+po, -0.5ky-2po]
        - ref: mirror_matrix_outer_bottom
          shift: [-0.5kx-po, -0.5ky-2po]
      fillet: sr
  board:
    - name: _main
    - operation: subtract
      name: _magnets
    - operation: subtract
      name: _battery_cutout
    - operation: subtract
      name: _mount_holes

    - name: _main_mirror
    - operation: subtract
      name: _magnets_mirror
    - operation: subtract
      name: _battery_cutout_mirror
    - operation: subtract
      name: _mount_holes_mirror
  combo:
    - name: board
    - operation: subtract
      name: _keys
pcbs:
  kbd:
    outlines:
      main:
        outline: board
    footprints:
      keys:
        what: kailh_x
        where: true
        params:
          from: "{{column_net}}"
          to: "{{colrow}}"
      diode:
        what: diode_sod323
        where: true
        params:
          from: "{{colrow}}"
          to: "{{row_net}}"
        adjust:
          shift: [0, 6]
          rotate: 180
      power_gnd:
        what: thru_hole_pad
        params:
          net: GND
        where:
          ref: thumbs_gamma_cluster
          shift: [0.5kx+p-3, 2ky+1.4]
      power_vcc_mirror:
        what: thru_hole_pad
        params:
          net: VCC
        where:
          ref: mirror_thumbs_gamma_cluster
          shift: [0.5kx+p-3, 2ky-1.4]
      power_gnd_mirror:
        what: thru_hole_pad
        params:
          net: GND
        where:
          ref: mirror_thumbs_gamma_cluster
          shift: [0.5kx+p-3, 2ky+1.4]
      power_vcc:
        what: thru_hole_pad
        params:
          net: VCC
        where:
          ref: thumbs_gamma_cluster
          shift: [0.5kx+p-3, 2ky-1.4]

      mcu:
        what: xiao_nrf52840
        where:
          ref: matrix_outer_top
          shift: [0.6kx, 0.8ky-1]
          rotate: 90
      mcu_mirror:
        what: xiao_nrf52840
        where:
          ref: mirror_matrix_outer_top
          shift: [0.6kx, 0.8ky-1+17.78]
          rotate: 90
