units:
  # Keycap
  krx: 16.5 # Keycap raw width
  kry: 16.5 # Keycap raw height
  p: 1.27 # Offset between keycaps
  po: 1.6 # Offset between keycaps and outline
  # Keycap
  kx: krx + p # Keycap width
  ky: kry + p # Keycap height
  sd: 2.2 # Screw diameter

points:
  zones:
    matrix:
      anchor:
        shift: [100, -100]
      key:
        padding: 1ky
        spread: 1kx
      columns:
        outer:
          key:
            column_net: P0
            mirror.column_net: P0_mirror
        pinky:
          key:
            splay: 0
            column_net: P1
            mirror.column_net: P1_mirror
        ring:
          key:
            stagger: 0.7ky
            column_net: P2
            mirror.column_net: P2_mirror
        middle:
          key:
            stagger: 0.5ky
            column_net: P3
            mirror.column_net: P3_mirror
        index:
          key:
            stagger: -0.2ky
            column_net: P4
            mirror.column_net: P4_mirror
        inner:
          key:
            column_net: P5
            mirror.column_net: P5_mirror
      rows:
        bottom:
          row_net: P9
          mirror.row_net: P9_mirror
        home:
          row_net: P8
          mirror.row_net: P8_mirror
        top:
          row_net: P7
          mirror.row_net: P7_mirror
    thumbs:
      key:
        padding: 1ky
        spread: 1kx
      anchor:
        ref: matrix_middle_bottom
        shift: [1.2kx, -1.2ky]
      columns:
        alpha:
          key:
            column_net: P3
            mirror.column_net: P3_mirror
        beta:
          key:
            column_net: P4
            mirror.column_net: P4_mirror
        gamma:
          key:
            column_net: P5
            mirror.column_net: P5_mirror
      rows:
        cluster:
          row_net: P6
          mirror.row_net: P6_mirror

  rotate: -0
  mirror: &mirror
    ref: matrix_inner_home
    distance: 4kx+20+2
outlines:
  _keys:
    - what: rectangle
      where: true
      size: [krx, kry]

  _main:
    - what: polygon
      operation: stack
      points:
        - ref: matrix_outer_top
          shift: [-0.5kx-po, 1.7ky+2po]
        - ref: matrix_index_top
          shift: [-0.5kx+po, 0.7ky+2po]
        - ref: matrix_index_top
          shift: [-0.5kx+po, 0.5ky+po]
        - ref: matrix_inner_top
          shift: [1.55kx-po, 0.5ky+po]
        - ref: matrix_inner_top
          shift: [1.55kx-po, 0.7ky+2po]
        - ref: matrix_inner_top
          shift: [1.55kx+po, 0.7ky+2po]
        # magnet top
        - ref: matrix_inner_home
          shift: [2kx, 15]
        # magnet bottom
        - ref: matrix_inner_home
          shift: [2kx + 10, -15]
        - ref: thumbs_gamma_cluster
          shift: [0.8kx + 10, -0.5ky-2po]
        - ref: matrix_outer_bottom
          shift: [-0.5kx-po, -0.5ky-2po]
      fillet: po
  _main_mirror:
    - what: polygon
      operation: stack
      points:
        - ref: mirror_matrix_outer_top
          shift: [-0.5kx-po, 1.7ky+2po]
        - ref: mirror_matrix_index_top
          shift: [-0.5kx+po, 0.7ky+2po]
        - ref: mirror_matrix_index_top
          shift: [-0.5kx+po, 0.5ky+po]
        - ref: mirror_matrix_inner_top
          shift: [1.55kx-po, 0.5ky+po]
        - ref: mirror_matrix_inner_top
          shift: [1.55kx-po, 0.7ky+2po]
        - ref: mirror_matrix_inner_top
          shift: [1.55kx+po, 0.7ky+2po]
        # magnet top
        - ref: mirror_matrix_inner_home
          shift: [2kx, 15]
        # magnet bottom
        - ref: mirror_matrix_inner_home
          shift: [2kx + 10, -15]
        - ref: mirror_thumbs_gamma_cluster
          shift: [0.8kx + 10, -0.5ky-2po]
        - ref: mirror_matrix_outer_bottom
          shift: [-0.5kx-po, -0.5ky-2po]
      fillet: po
  _join:
    - what: polygon
      operation: stack
      points:
        - ref: matrix_inner_home
          shift: [2kx+10, -18]
        - ref: matrix_inner_home
          shift: [2kx+10, -44]
        - ref: mirror_matrix_inner_home
          shift: [2kx+10, -44]
        - ref: mirror_matrix_inner_home
          shift: [2kx+10, -18]
  board:
    - name: _main
    - name: _main_mirror
    - name: _join
  combo:
    - name: board
    - operation: subtract
      name: _keys
pcbs:
  kbd:
    outlines:
      main:
        outline: board
    footprints:
      keys:
        what: kailh_x
        where: true
        params:
          from: "{{column_net}}"
          to: "{{colrow}}"
      diode:
        what: diode_sod323
        where: true
        params:
          from: "{{colrow}}"
          to: "{{row_net}}"
        adjust:
          shift: [0, -5]
          rotate: 180
      via:
        what: via
        where: true
        params:
          net: GND
        adjust:
          shift: [0, 3]

      battery_power_mcu:
        what: thru_hole_pad
        params:
          net: BAT_VCC
        where:
          ref: matrix_pinky_top
          shift: [-0.2kx, 0.8ky]
      battery_power_mcu_text:
        what: text
        where:
          ref: matrix_pinky_top
          shift: [-0.2kx+1.5, 0.8ky]
        params:
          layer: F.SilkS
          text: "BAT+"
          justify: "left"

      battery_power_mcu_mirror:
        what: thru_hole_pad
        params:
          net: BAT_VCC_MIRROR
        where:
          ref: mirror_matrix_pinky_top
          shift: [-0.2kx, 0.8ky]
      battery_power_mcu_text_mirror:
        what: text
        where:
          ref: mirror_matrix_pinky_top
          shift: [-0.2kx+1.5, 0.8ky]
        params:
          layer: F.SilkS
          text: "BAT+"
          justify: "right"

      battery_power:
        what: thru_hole_pad
        params:
          net: BAT_VCC
        where:
          ref: matrix_middle_bottom
          shift: [-0.3kx, -1.4-0.9ky]
      battery_power_text:
        what: text
        where:
          ref: matrix_middle_bottom
          shift: [-0.3kx+1.5, -1.4-0.9ky]
        params:
          layer: F.SilkS
          text: "BAT+"
          justify: "left"

      battery_power_mirror:
        what: thru_hole_pad
        params:
          net: BAT_VCC_MIRROR
        where:
          ref: mirror_matrix_middle_bottom
          shift: [-0.3kx, -1.4-0.9ky]
      battery_power_text_mirror:
        what: text
        where:
          ref: mirror_matrix_middle_bottom
          shift: [-0.3kx+1.5, -1.4-0.9ky]
        params:
          layer: F.SilkS
          text: "BAT+"
          justify: "right"

      battery_power_gnd:
        what: thru_hole_pad
        params:
          net: GND
        where:
          ref: matrix_middle_bottom
          shift: [-0.3kx, 1.4-0.9ky]
      battery_power_gnd_text:
        what: text
        where:
          ref: matrix_middle_bottom
          shift: [-0.3kx+1.5, 1.4-0.9ky]
        params:
          layer: F.SilkS
          text: "BAT-"
          justify: "left"

      battery_power_gnd_mirror:
        what: thru_hole_pad
        params:
          net: GND
        where:
          ref: mirror_matrix_middle_bottom
          shift: [-0.3kx, 1.4-0.9ky]
      battery_power_gnd_text_mirror:
        what: text
        where:
          ref: mirror_matrix_middle_bottom
          shift: [-0.3kx+1.5, 1.4-0.9ky]
        params:
          layer: F.SilkS
          text: "BAT-"
          justify: "right"

      power_gnd:
        what: thru_hole_pad
        params:
          net: GND
        where:
          ref: thumbs_gamma_cluster
          shift: [0.8kx + 10 - 2, -1.4]
      power_gnd_text:
        what: text
        where:
          ref: thumbs_gamma_cluster
          shift: [0.8kx + 6, -1.4]
        params:
          layer: B.SilkS
          text: "GND"
          justify: "left mirror"

      power_gnd_mirror:
        what: thru_hole_pad
        params:
          net: GND
        where:
          ref: mirror_thumbs_gamma_cluster
          shift: [0.8kx + 10 - 2, -1.4]
      power_gnd_text_mirror:
        what: text
        where:
          ref: mirror_thumbs_gamma_cluster
          shift: [0.8kx + 6, -1.4]
        params:
          layer: B.SilkS
          text: "GND"
          justify: "right mirror"

      power_vcc:
        what: thru_hole_pad
        params:
          net: RAW
        where:
          ref: thumbs_gamma_cluster
          shift: [0.8kx + 10 - 2, 1.4]
      power_vcc_text:
        what: text
        where:
          ref: thumbs_gamma_cluster
          shift: [0.8kx + 6, 1.4]
        params:
          layer: B.SilkS
          text: "+5V"
          justify: "left mirror"

      power_vcc_mirror:
        what: thru_hole_pad
        params:
          net: RAW
        where:
          ref: mirror_thumbs_gamma_cluster
          shift: [0.8kx + 10 - 2, 1.4]
      power_vcc_text_mirror:
        what: text
        where:
          ref: mirror_thumbs_gamma_cluster
          shift: [0.8kx + 6, 1.4]
        params:
          layer: B.SilkS
          text: "+5V"
          justify: "right mirror"

      mcu:
        what: xiao_nrf52840
        where:
          ref: matrix_outer_top
          shift: [0.6kx, 0.8ky - 2]
          rotate: 90
      mcu_mirror:
        what: xiao_nrf52840
        params:
          P0: P0_mirror
          P1: P1_mirror
          P2: P2_mirror
          P3: P3_mirror
          P4: P4_mirror
          P5: P5_mirror
          P6: P6_mirror
          P7: P7_mirror
          P8: P8_mirror
          P9: P9_mirror
          P10: P10_mirror
          VCC: VCC_mirror
          RAW: RAW
          GND: GND
        where:
          ref: mirror_matrix_outer_top
          shift: [0.6kx, 0.8ky-2+17.78]
          rotate: 90

      mount_hole_inner_bottom:
        what: mounthole
        params:
          diameter: sd
        where:
          ref: matrix_inner_bottom
          shift: [1kx, 0]

      mount_hole_inner_top:
        what: mounthole
        params:
          diameter: sd
        where:
          ref: matrix_inner_top
          shift: [0.8kx, 0]

      mount_hole_thumb_bottom:
        what: mounthole
        params:
          diameter: sd
        where:
          ref: thumbs_gamma_cluster
          shift: [0.8kx, -0.3ky]

      mount_hole_pinky:
        what: mounthole
        params:
          diameter: sd
        where:
          ref: matrix_pinky_top
          shift: [0kx, 1.25ky]

      mount_hole_middle:
        what: mounthole
        params:
          diameter: sd
        where:
          ref: matrix_middle_bottom
          shift: [0.2kx, -0.75ky]

      mount_hole_inner_bottom_mirror:
        what: mounthole
        params:
          diameter: sd
        where:
          ref: mirror_matrix_inner_bottom
          shift: [1kx, 0]

      mount_hole_inner_top_mirror:
        what: mounthole
        params:
          diameter: sd
        where:
          ref: mirror_matrix_inner_top
          shift: [0.8kx, 0]

      mount_hole_thumb_bottom_mirror:
        what: mounthole
        params:
          diameter: sd
        where:
          ref: mirror_thumbs_gamma_cluster
          shift: [0.8kx, -0.3ky]

      mount_hole_pinky_mirror:
        what: mounthole
        params:
          diameter: sd
        where:
          ref: mirror_matrix_pinky_top
          shift: [0kx, 1.25ky]

      mount_hole_middle_mirror:
        what: mounthole
        params:
          diameter: sd
        where:
          ref: mirror_matrix_middle_bottom
          shift: [0.2kx, -0.75ky]

      magnet_bottom:
        what: magnet_hole
        params:
          net: GND
        where:
          ref: matrix_inner_home
          shift: [1.5kx + 10, -15]

      magnet_top:
        what: magnet_hole
        params:
          net: GND
        where:
          ref: matrix_inner_home
          shift: [1.5kx, 15]

      magnet_bottom_mirror:
        what: magnet_hole
        params:
          net: GND
        where:
          ref: mirror_matrix_inner_home
          shift: [1.5kx + 10, -15]

      magnet_top_mirror:
        what: magnet_hole
        params:
          net: GND
        where:
          ref: mirror_matrix_inner_home
          shift: [1.5kx, 15]

      # Name
      project_name:
        what: text
        where:
          ref: matrix_ring_top
          shift: [-0.5kx, 0.8ky]
        params:
          layer: F.SilkS
          text: "crabapplepad v1.0\\nby @kumekay 2023\\nleft side"
          justify: left

      project_name_mirror:
        what: text
        where:
          ref: mirror_matrix_ring_top
          shift: [-0.5kx, 0.8ky]
        params:
          layer: F.SilkS
          text: "crabapplepad v1.0\\nby @kumekay 2023\\nright side"
          justify: right

      jlcpcd_order_id:
        what: text
        where:
          ref: matrix_ring_bottom
          shift: [0, -0.9ky]
        params:
          text: "JLCJLCJLCJLC"
          justify: left

      # Breakers
      # mouse_bite_top:
      #   what: hole_array
      #   params:
      #     x_count: 2
      #     x_spacing: 2
      #     y_count: 17
      #   where:
      #     ref: matrix_inner_home
      #     shift: [2kx+10, -18]

      # mouse_bite_bottom:
      #   what: hole_array
      #   params:
      #     x_count: 2
      #     x_spacing: 2
      #     y_count: 8
      #   where:
      #     ref: matrix_inner_home
      #     shift: [2kx+10, -37]
