units:
  # Keycap
  krx: 18 # Keycap raw width
  kry: 18 # Keycap raw height
  po: 1.6 # Offset between keycaps and outline

  # Keycap spacing
  kx: 19
  ky: 19

  sd: 2.2 # Screw diameter
  ps: 2.54 # Pin spacing

points:
  zones:
    matrix:
      anchor:
        shift: [100, -100]
      key:
        padding: 1ky
        spread: 1kx
        tags:
      columns:
        outer:
          key:
            column_net: P031
            mirror.column_net: P017
        pinky:
          key:
            splay: 0
            column_net: P029
            mirror.column_net: P020
        ring:
          key:
            stagger: 0.7ky
            column_net: P002
            mirror.column_net: P022
        middle:
          key:
            stagger: 0.5ky
            column_net: P115
            mirror.column_net: P024
        index:
          key:
            stagger: -0.2ky
            column_net: P113
            mirror.column_net: P100
        inner:
          key:
            column_net: P111
            mirror.column_net: P011
      rows:
        bottom:
          row_net: P104
          mirror.row_net: P104
        home:
          row_net: P106
          mirror.row_net: P106
        top:
          row_net: P010
          mirror.row_net: P010
    thumbs:
      key:
        padding: 1ky
        spread: 1kx
      anchor:
        ref: matrix_middle_bottom
        shift: [1.2kx, -1.2ky]
      columns:
        alpha:
          key:
            column_net: P115
            mirror.column_net: P024
        beta:
          key:
            column_net: P113
            mirror.column_net: P100
        gamma:
          key:
            column_net: P111
            mirror.column_net: P011
      rows:
        cluster:
          row_net: P009
          mirror.row_net: P009

  rotate: -19.2
  mirror: &mirror
    ref: matrix_inner_home
    distance: 60 + 2po
outlines:
  _keys:
    - what: rectangle
      where: true
      size: [krx, kry]

  _main:
    - what: polygon
      operation: stack
      points:
        - ref: matrix_outer_top
          shift: [-0.5kx-po, 1.7ky+2po]
        - ref: matrix_inner_top
          shift: [1.55kx-po, 0.7ky+2po]
        - ref: matrix_inner_top
          shift: [1.55kx+po, 0.7ky+2po]
        - ref: thumbs_gamma_cluster
          shift: [0.8kx + 10, -0.5ky-2po]
        - ref: matrix_outer_bottom
          shift: [-0.5kx-po, -0.5ky-2po]
      # fillet: po
  _main_mirror:
    - what: polygon
      operation: stack
      points:
        - ref: mirror_matrix_outer_top
          shift: [-0.5kx-po, 1.7ky+2po]
        - ref: mirror_matrix_inner_top
          shift: [1.55kx-po, 0.7ky+2po]
        - ref: mirror_matrix_inner_top
          shift: [1.55kx+po, 0.7ky+2po]
        - ref: mirror_thumbs_gamma_cluster
          shift: [0.8kx + 10, -0.5ky-2po]
        - ref: mirror_matrix_outer_bottom
          shift: [-0.5kx-po, -0.5ky-2po]
      # fillet: po
  _join:
    - what: polygon
      operation: stack
      points:
        - ref: matrix_inner_top
          shift: [1.55kx+po, 0.7ky+2po]
        - ref: mirror_matrix_inner_top
          shift: [1.55kx+po, 0.7ky+2po]
        - ref: mirror_thumbs_gamma_cluster
          shift: [0.8kx + 10, -0.5ky-2po]
        - ref: thumbs_gamma_cluster
          shift: [0.8kx + 10, -0.5ky-2po]

  board:
    - name: _main
    - name: _main_mirror
    - name: _join
  # combo:
  #   - name: board
  #   - operation: subtract
  #     name: _keys
pcbs:
  kbd:
    outlines:
      main:
        outline: board
    footprints:
      keys:
        what: mx_choc
        where: true
        params:
          from: "{{column_net}}"
          to: "{{colrow}}"
      diode:
        what: diode_sod323
        # Use "mirror" for the  left side too
        # to select left side correctly without tag
        where:
          - /mirror_matrix_.*/
          - /mirror_thumbs_.*/
        asym: clone
        params:
          from: "{{colrow}}"
          to: "{{row_net}}"
          side: "F"
        adjust:
          shift: [kx/2, ky/2-3]
          rotate: -90

      diode_mirror:
        what: diode_sod323
        where:
          - /mirror_matrix_.*/
          - /mirror_thumbs_.*/
        asym: source
        params:
          from: "{{colrow}}"
          to: "{{row_net}}"
          side: "F"
        adjust:
          shift: [kx/2, ky/2-3]
          rotate: 90

      # via:
      #   what: via
      #   where: true
      #   params:
      #     net: GND
      #   adjust:
      #     shift: [0, 3]
      mcu:
        what: promicro_nrf
        where:
          ref.aggregate.parts: [matrix_index_top, mirror_matrix_index_top]
          shift: [0, -20]
          rotate: -90

      col_outer:
        what: thru_hole_pad
        params:
          net: P031
        where:
          ref: thumbs_gamma_cluster
          shift: [-0.5kx, 0.6ky + po + 9ps]

      col_pinky:
        what: thru_hole_pad
        params:
          net: P029
        where:
          ref: thumbs_gamma_cluster
          shift: [-0.5kx, 0.6ky + po + 8ps]

      col_ring:
        what: thru_hole_pad
        params:
          net: P002
        where:
          ref: thumbs_gamma_cluster
          shift: [-0.5kx, 0.6ky + po + 7ps]

      col_middle:
        what: thru_hole_pad
        params:
          net: P115
        where:
          ref: thumbs_gamma_cluster
          shift: [-0.5kx, 0.6ky + po + 6ps]

      col_index:
        what: thru_hole_pad
        params:
          net: P113
        where:
          ref: thumbs_gamma_cluster
          shift: [-0.5kx, 0.6ky + po + 5ps]

      col_inner:
        what: thru_hole_pad
        params:
          net: P111
        where:
          ref: thumbs_gamma_cluster
          shift: [-0.5kx, 0.6ky + po + 4ps]

      row_top:
        what: thru_hole_pad
        params:
          net: P010
        where:
          ref: thumbs_gamma_cluster
          shift: [-0.5kx, 0.6ky + po + 3ps]

      row_home:
        what: thru_hole_pad
        params:
          net: P106
        where:
          ref: thumbs_gamma_cluster
          shift: [-0.5kx, 0.6ky + po + 2ps]

      row_bottom:
        what: thru_hole_pad
        params:
          net: P104
        where:
          ref: thumbs_gamma_cluster
          shift: [-0.5kx, 0.6ky + po + 1ps]

      row_thumbs:
        what: thru_hole_pad
        params:
          net: P009
        where:
          ref: thumbs_gamma_cluster
          shift: [-0.5kx, 0.6ky + po]

      battery_power:
        what: thru_hole_pad
        params:
          net: BAT_VCC
        where:
          ref.aggregate.parts: [matrix_index_top, mirror_matrix_index_top]
          shift: [-2, -40]
      battery_power_text:
        what: text
        where:
          ref.aggregate.parts: [matrix_index_top, mirror_matrix_index_top]
          shift: [-3.5, -40]
        params:
          layer: F.SilkS
          text: "BAT+"
          justify: "right"

      battery_power_gnd:
        what: thru_hole_pad
        params:
          net: GND
        where:
          ref.aggregate.parts: [matrix_index_top, mirror_matrix_index_top]
          shift: [2, -40]
      battery_power_gnd_text:
        what: text
        where:
          ref.aggregate.parts: [matrix_index_top, mirror_matrix_index_top]
          shift: [3.5, -40]
        params:
          layer: F.SilkS
          text: "BAT-"
          justify: "left"

      mount_hole_inner_bottom:
        what: mounthole
        params:
          diameter: sd
        where:
          ref: matrix_inner_bottom
          shift: [1kx, 0]

      mount_hole_inner_top:
        what: mounthole
        params:
          diameter: sd
        where:
          ref: matrix_inner_top
          shift: [0.8kx, 0]

      mount_hole_thumb_bottom:
        what: mounthole
        params:
          diameter: sd
        where:
          ref: thumbs_gamma_cluster
          shift: [0.8kx, -0.3ky]

      mount_hole_pinky:
        what: mounthole
        params:
          diameter: sd
        where:
          ref: matrix_pinky_top
          shift: [0kx, 1.25ky]

      mount_hole_middle:
        what: mounthole
        params:
          diameter: sd
        where:
          ref: matrix_middle_bottom
          shift: [0.2kx, -0.75ky]

      mount_hole_inner_bottom_mirror:
        what: mounthole
        params:
          diameter: sd
        where:
          ref: mirror_matrix_inner_bottom
          shift: [1kx, 0]

      mount_hole_inner_top_mirror:
        what: mounthole
        params:
          diameter: sd
        where:
          ref: mirror_matrix_inner_top
          shift: [0.8kx, 0]

      mount_hole_thumb_bottom_mirror:
        what: mounthole
        params:
          diameter: sd
        where:
          ref: mirror_thumbs_gamma_cluster
          shift: [0.8kx, -0.3ky]

      mount_hole_pinky_mirror:
        what: mounthole
        params:
          diameter: sd
        where:
          ref: mirror_matrix_pinky_top
          shift: [0kx, 1.25ky]

      mount_hole_middle_mirror:
        what: mounthole
        params:
          diameter: sd
        where:
          ref: mirror_matrix_middle_bottom
          shift: [0.2kx, -0.75ky]

      # Name
      project_name:
        what: text
        where:
          ref: matrix_ring_top
          shift: [-0.5kx, 0.8ky]
        params:
          layer: F.SilkS
          text: "crabapplepad v2.0\\nby @kumekay 2024\\nleft side"
          justify: left

      project_name_mirror:
        what: text
        where:
          ref: mirror_matrix_ring_top
          shift: [-0.5kx, 0.8ky]
        params:
          layer: F.SilkS
          text: "crabapplepad v2.0\\nby @kumekay 2024\\nright side"
          justify: right

      jlcpcd_order_id:
        what: text
        where:
          ref: matrix_ring_bottom
          shift: [0, -0.9ky]
        params:
          text: "JLCJLCJLCJLC"
          justify: left

      # Breakers
      # mouse_bite_top:
      #   what: hole_array
      #   params:
      #     x_count: 2
      #     x_spacing: 2
      #     y_count: 17
      #   where:
      #     ref: matrix_inner_home
      #     shift: [2kx+10, -18]

      # mouse_bite_bottom:
      #   what: hole_array
      #   params:
      #     x_count: 2
      #     x_spacing: 2
      #     y_count: 8
      #   where:
      #     ref: matrix_inner_home
      #     shift: [2kx+10, -37]
