meta:
  engine: 4.1.0
  name: crabapplepad
  version: 2.0
  author: kumekay
  url: https://github.com/kumekay/crabapplepad/tree/v2

units:
  # Keycap
  krx: 18 # Keycap raw width
  kry: 18 # Keycap raw height
  po: 1.6 # Offset between keycaps and outline

  # Keycap spacing
  kx: 19
  ky: 19

  sd: 2.2 # Screw diameter
  ps: 2.54 # Pin spacing

  # MCU
  pos: -20 - 8.7ps # Hole offset from bottom pin

points:
  zones:
    matrix:
      anchor:
        shift: [100, -100]
      key:
        padding: 1ky
        spread: 1kx
        tags:
      columns:
        outer:
          key:
            column_net: P031
            mirror.column_net: P017
        pinky:
          key:
            splay: 0
            column_net: P029
            mirror.column_net: P020
        ring:
          key:
            stagger: 0.7ky
            column_net: P002
            mirror.column_net: P022
        middle:
          key:
            stagger: 0.5ky
            column_net: P115
            mirror.column_net: P024
        index:
          key:
            stagger: -0.2ky
            column_net: P113
            mirror.column_net: P100
        inner:
          key:
            column_net: P111
            mirror.column_net: P011
      rows:
        bottom:
          row_net: P104
          mirror.row_net: P104
        home:
          row_net: P106
          mirror.row_net: P106
        top:
          row_net: P010
          mirror.row_net: P010
    thumbs:
      key:
        padding: 1ky
        spread: 1kx
      anchor:
        ref: matrix_middle_bottom
        shift: [1.2kx, -1.2ky]
      columns:
        alpha:
          key:
            column_net: P115
            mirror.column_net: P024
        beta:
          key:
            column_net: P113
            mirror.column_net: P100
        gamma:
          key:
            column_net: P111
            mirror.column_net: P011
      rows:
        cluster:
          row_net: P009
          mirror.row_net: P009

  rotate: -22
  mirror: &mirror
    ref: matrix_inner_home
    distance: 74 + 2po
outlines:
  _keys:
    - what: rectangle
      where: true
      size: [krx, kry]

  board:
    - what: polygon
      operation: add
      fillet: po
      points:
        - ref: matrix_outer_top
          shift: [-0.5kx-po, 0.5ky+1po]
        - ref: matrix_middle_top
          shift: [-0.5kx-po, 0.5ky+2po]
        - ref: matrix_inner_top
          shift: [0.5kx+po, 0.7ky+2po]
        - ref: mirror_matrix_inner_top
          shift: [0.5kx+po, 0.7ky+2po]
        - ref: mirror_matrix_middle_top
          shift: [-0.5kx-po, 0.5ky+2po]
        - ref: mirror_matrix_outer_top
          shift: [-0.5kx-po, 0.5ky+1po]
        - ref: mirror_matrix_outer_bottom
          shift: [-0.5kx-po, -0.5ky-2po]
        - ref: mirror_thumbs_gamma_cluster
          shift: [0.5kx + po, -0.5ky-2po]
        - ref: thumbs_gamma_cluster
          shift: [0.5kx + po, -0.5ky-2po]
        - ref: matrix_outer_bottom
          shift: [-0.5kx-po, -0.5ky-2po]

    # USB cutout
    - what: rectangle
      operation: subtract
      where:
        ref.aggregate.parts: [matrix_index_top, mirror_matrix_index_top]
        shift: [0, ps]
      size: [14, 8]
      fillet: po

    # Left top cutout
    - what: rectangle
      operation: subtract
      where:
        ref.aggregate.parts: [matrix_index_top, mirror_matrix_index_top]
        shift: [-15, -10]
      size: [2, 16]
      fillet: .8

    # Right top cutout
    - what: rectangle
      operation: subtract
      where:
        ref.aggregate.parts: [matrix_index_top, mirror_matrix_index_top]
        shift: [15, -10]
      size: [2, 16]
      fillet: .8

    # Left bottom cutout
    - what: rectangle
      operation: subtract
      where:
        ref.aggregate.parts: [matrix_index_top, mirror_matrix_index_top]
        shift: [-15, -58]
      size: [2, 29]
      fillet: .8

    # Right bottom cutout
    - what: rectangle
      operation: subtract
      where:
        ref.aggregate.parts: [matrix_index_top, mirror_matrix_index_top]
        shift: [15, -58]
      size: [2, 29]
      fillet: .8

    # Bottom cutout
    - what: rectangle
      operation: subtract
      where:
        ref.aggregate.parts: [matrix_index_top, mirror_matrix_index_top]
        shift: [0, -90]
      size: [32, 30]
      fillet: po

  combo:
    - name: board
    - operation: subtract
      name: _keys

  key_holder:
    - what: rectangle
      where: true
      size: [krx+2, kry+2]
      fillet: 2
    - what: rectangle
      where: true
      size: [14.1, 14.1]
      operation: subtract

pcbs:
  kbd:
    template: kicad8
    outlines:
      main:
        outline: board
    footprints:
      keys:
        what: mx_choc
        where: true
        params:
          from: "{{column_net}}"
          to: "{{colrow}}"
      diode:
        what: diode_sod323
        # Use "mirror" for the  left side too
        # to select left side correctly without tag
        where:
          - /mirror_matrix_.*/
          - /mirror_thumbs_.*/
        asym: clone
        params:
          from: "{{colrow}}"
          to: "{{row_net}}"
          side: "F"
          handSoldering: true
        adjust:
          shift: [kx/2, 4]
          rotate: -90

      via_diode:
        what: via
        where:
          - /mirror_matrix_.*/
          - /mirror_thumbs_.*/
        asym: clone
        params:
          net: "{{row_net}}"
        adjust:
          shift: [kx/2, 7]

      diode_mirror:
        what: diode_sod323
        where:
          - /mirror_matrix_.*/
          - /mirror_thumbs_.*/
        asym: source
        params:
          from: "{{colrow}}"
          to: "{{row_net}}"
          side: "F"
          handSoldering: true
        adjust:
          shift: [kx/2, 4]
          rotate: 90

      via_diode_mirror:
        what: via
        where:
          - /mirror_matrix_.*/
          - /mirror_thumbs_.*/
        asym: source
        params:
          net: "{{row_net}}"
        adjust:
          shift: [kx/2, 7]

      via:
        what: via
        where: true
        params:
          net: GND
        adjust:
          shift: [-0.4kx, 0.1ky]

      mcu:
        what: promicro_nrf
        where:
          ref.aggregate.parts: [matrix_index_top, mirror_matrix_index_top]
          shift: [0, -20]
          rotate: -90

      # Left side keys
      col_outer:
        what: thru_hole_pad
        params:
          net: P031
        where:
          ref.aggregate.parts: [matrix_index_top, mirror_matrix_index_top]
          shift: [-19, pos + 9ps]

      col_pinky:
        what: thru_hole_pad
        params:
          net: P029
        where:
          ref.aggregate.parts: [matrix_index_top, mirror_matrix_index_top]
          shift: [-19, pos + 8ps]

      col_ring:
        what: thru_hole_pad
        params:
          net: P002
        where:
          ref.aggregate.parts: [matrix_index_top, mirror_matrix_index_top]
          shift: [-19, pos + 7ps]

      col_middle:
        what: thru_hole_pad
        params:
          net: P115
        where:
          ref.aggregate.parts: [matrix_index_top, mirror_matrix_index_top]
          shift: [-19, pos + 6ps]

      col_index:
        what: thru_hole_pad
        params:
          net: P113
        where:
          ref.aggregate.parts: [matrix_index_top, mirror_matrix_index_top]
          shift: [-19, pos + 5ps]

      col_inner:
        what: thru_hole_pad
        params:
          net: P111
        where:
          ref.aggregate.parts: [matrix_index_top, mirror_matrix_index_top]
          shift: [-19, pos + 4ps]

      row_top:
        what: thru_hole_pad
        params:
          net: P010
        where:
          ref.aggregate.parts: [matrix_index_top, mirror_matrix_index_top]
          shift: [-19, pos + 3ps]

      row_home:
        what: thru_hole_pad
        params:
          net: P106
        where:
          ref.aggregate.parts: [matrix_index_top, mirror_matrix_index_top]
          shift: [-19, pos + 2ps]

      row_bottom:
        what: thru_hole_pad
        params:
          net: P104
        where:
          ref.aggregate.parts: [matrix_index_top, mirror_matrix_index_top]
          shift: [-19, pos + 1ps]

      row_thumbs:
        what: thru_hole_pad
        params:
          net: P009
        where:
          ref.aggregate.parts: [matrix_index_top, mirror_matrix_index_top]
          shift: [-19, pos + 0ps]

      # Left side PCB

      col_outer_pcb:
        what: thru_hole_pad
        params:
          net: P031
        where:
          ref.aggregate.parts: [matrix_index_top, mirror_matrix_index_top]
          shift: [-11, pos + 9ps]

      col_pinky_pcb:
        what: thru_hole_pad
        params:
          net: P029
        where:
          ref.aggregate.parts: [matrix_index_top, mirror_matrix_index_top]
          shift: [-11, pos + 8ps]

      col_ring_pcb:
        what: thru_hole_pad
        params:
          net: P002
        where:
          ref.aggregate.parts: [matrix_index_top, mirror_matrix_index_top]
          shift: [-11, pos + 7ps]

      col_middle_pcb:
        what: thru_hole_pad
        params:
          net: P115
        where:
          ref.aggregate.parts: [matrix_index_top, mirror_matrix_index_top]
          shift: [-11, pos + 6ps]

      col_index_pcb:
        what: thru_hole_pad
        params:
          net: P113
        where:
          ref.aggregate.parts: [matrix_index_top, mirror_matrix_index_top]
          shift: [-11, pos + 5ps]

      col_inner_pcb:
        what: thru_hole_pad
        params:
          net: P111
        where:
          ref.aggregate.parts: [matrix_index_top, mirror_matrix_index_top]
          shift: [-11, pos + 4ps]

      row_top_pcb:
        what: thru_hole_pad
        params:
          net: P010
        where:
          ref.aggregate.parts: [matrix_index_top, mirror_matrix_index_top]
          shift: [-11, pos + 3ps]

      row_home_pcb:
        what: thru_hole_pad
        params:
          net: P106
        where:
          ref.aggregate.parts: [matrix_index_top, mirror_matrix_index_top]
          shift: [-11, pos + 2ps]

      row_bottom_pcb:
        what: thru_hole_pad
        params:
          net: P104
        where:
          ref.aggregate.parts: [matrix_index_top, mirror_matrix_index_top]
          shift: [-11, pos + ps]

      row_thumbs_pcb:
        what: thru_hole_pad
        params:
          net: P009
        where:
          ref.aggregate.parts: [matrix_index_top, mirror_matrix_index_top]
          shift: [-11, pos]

      # Right side keys
      mirror_col_outer:
        what: thru_hole_pad
        params:
          net: P017
        where:
          ref.aggregate.parts: [matrix_index_top, mirror_matrix_index_top]
          shift: [19, pos + 9ps]

      mirror_col_pinky:
        what: thru_hole_pad
        params:
          net: P020
        where:
          ref.aggregate.parts: [matrix_index_top, mirror_matrix_index_top]
          shift: [19, pos + 8ps]

      mirror_col_ring:
        what: thru_hole_pad
        params:
          net: P022
        where:
          ref.aggregate.parts: [matrix_index_top, mirror_matrix_index_top]
          shift: [19, pos + 7ps]

      mirror_col_middle:
        what: thru_hole_pad
        params:
          net: P024
        where:
          ref.aggregate.parts: [matrix_index_top, mirror_matrix_index_top]
          shift: [19, pos + 6ps]

      mirror_col_index:
        what: thru_hole_pad
        params:
          net: P100
        where:
          ref.aggregate.parts: [matrix_index_top, mirror_matrix_index_top]
          shift: [19, pos + 5ps]

      mirror_col_inner:
        what: thru_hole_pad
        params:
          net: P011
        where:
          ref.aggregate.parts: [matrix_index_top, mirror_matrix_index_top]
          shift: [19, pos + 4ps]

      mirror_row_top:
        what: thru_hole_pad
        params:
          net: P010
        where:
          ref.aggregate.parts: [matrix_index_top, mirror_matrix_index_top]
          shift: [19, pos + 3ps]

      mirror_row_home:
        what: thru_hole_pad
        params:
          net: P106
        where:
          ref.aggregate.parts: [matrix_index_top, mirror_matrix_index_top]
          shift: [19, pos + 2ps]

      mirror_row_bottom:
        what: thru_hole_pad
        params:
          net: P104
        where:
          ref.aggregate.parts: [matrix_index_top, mirror_matrix_index_top]
          shift: [19, pos + 1ps]

      mirror_row_thumbs:
        what: thru_hole_pad
        params:
          net: P009
        where:
          ref.aggregate.parts: [matrix_index_top, mirror_matrix_index_top]
          shift: [19, pos + 0ps]

      # Left side PCB

      mirror_col_outer_pcb:
        what: thru_hole_pad
        params:
          net: P017
        where:
          ref.aggregate.parts: [matrix_index_top, mirror_matrix_index_top]
          shift: [11, pos + 9ps]

      mirror_col_pinky_pcb:
        what: thru_hole_pad
        params:
          net: P020
        where:
          ref.aggregate.parts: [matrix_index_top, mirror_matrix_index_top]
          shift: [11, pos + 8ps]

      mirror_col_ring_pcb:
        what: thru_hole_pad
        params:
          net: P022
        where:
          ref.aggregate.parts: [matrix_index_top, mirror_matrix_index_top]
          shift: [11, pos + 7ps]

      mirror_col_middle_pcb:
        what: thru_hole_pad
        params:
          net: P024
        where:
          ref.aggregate.parts: [matrix_index_top, mirror_matrix_index_top]
          shift: [11, pos + 6ps]

      mirror_col_index_pcb:
        what: thru_hole_pad
        params:
          net: P100
        where:
          ref.aggregate.parts: [matrix_index_top, mirror_matrix_index_top]
          shift: [11, pos + 5ps]

      mirror_col_inner_pcb:
        what: thru_hole_pad
        params:
          net: P011
        where:
          ref.aggregate.parts: [matrix_index_top, mirror_matrix_index_top]
          shift: [11, pos + 4ps]

      mirror_row_top_pcb:
        what: thru_hole_pad
        params:
          net: P010
        where:
          ref.aggregate.parts: [matrix_index_top, mirror_matrix_index_top]
          shift: [11, pos + 3ps]

      mirror_row_home_pcb:
        what: thru_hole_pad
        params:
          net: P106
        where:
          ref.aggregate.parts: [matrix_index_top, mirror_matrix_index_top]
          shift: [11, pos + 2ps]

      mirror_row_bottom_pcb:
        what: thru_hole_pad
        params:
          net: P104
        where:
          ref.aggregate.parts: [matrix_index_top, mirror_matrix_index_top]
          shift: [11, pos + ps]

      mirror_row_thumbs_pcb:
        what: thru_hole_pad
        params:
          net: P009
        where:
          ref.aggregate.parts: [matrix_index_top, mirror_matrix_index_top]
          shift: [11, pos]

      # Misc

      battery_power:
        what: thru_hole_pad
        params:
          net: BAT_VCC
        where:
          ref.aggregate.parts: [matrix_index_top, mirror_matrix_index_top]
          shift: [-2, -38]
      battery_power_text:
        what: text
        where:
          ref.aggregate.parts: [matrix_index_top, mirror_matrix_index_top]
          shift: [-3.5, -38]
        params:
          layer: F.SilkS
          text: "BAT+"
          justify: "right"

      battery_power_gnd:
        what: thru_hole_pad
        params:
          net: GND
        where:
          ref.aggregate.parts: [matrix_index_top, mirror_matrix_index_top]
          shift: [2, -38]
      battery_power_gnd_text:
        what: text
        where:
          ref.aggregate.parts: [matrix_index_top, mirror_matrix_index_top]
          shift: [3.5, -38]
        params:
          layer: F.SilkS
          text: "BAT-"
          justify: "left"

      power_switch:
        what: power_switch_smd_side
        params:
          from: BAT_VCC
          to: RAW
        where:
          ref.aggregate.parts: [matrix_index_top, mirror_matrix_index_top]
          shift: [0, -72.7]
          rotate: -90

      # Mount holes
      # MCU

      mount_hole_mcu_left:
        what: mounthole
        params:
          diameter: sd
        where:
          ref.aggregate.parts: [matrix_index_top, mirror_matrix_index_top]
          shift: [-10.5, 1]

      mount_hole_mcu_right:
        what: mounthole
        params:
          diameter: sd
        where:
          ref.aggregate.parts: [matrix_index_top, mirror_matrix_index_top]
          shift: [10.5, 1]

      mount_hole_mcu_left_bottom:
        what: mounthole
        params:
          diameter: sd
        where:
          ref.aggregate.parts: [matrix_index_top, mirror_matrix_index_top]
          shift: [-10.5, -71]

      mount_hole_mcu_right_bottom:
        what: mounthole
        params:
          diameter: sd
        where:
          ref.aggregate.parts: [matrix_index_top, mirror_matrix_index_top]
          shift: [10.5, -71]

      mount_hole_inner_top:
        what: mounthole
        params:
          diameter: sd
        where:
          ref: matrix_inner_top
          shift: [0.25kx, 0.65ky]

      mount_hole_thumb_bottom:
        what: mounthole
        params:
          diameter: sd
        where:
          ref: thumbs_gamma_cluster
          shift: [0.75kx, -0.25ky]

      mount_hole_pinky:
        what: mounthole
        params:
          diameter: sd
        where:
          ref: matrix_pinky_top
          shift: [0.25kx, 0.75ky]

      mount_hole_middle:
        what: mounthole
        params:
          diameter: sd
        where:
          ref: matrix_middle_bottom
          shift: [-0.25kx, -0.75ky]

      mount_hole_inner_top_mirror:
        what: mounthole
        params:
          diameter: sd
        where:
          ref: mirror_matrix_inner_top
          shift: [0.25kx, 0.65ky]

      mount_hole_thumb_bottom_mirror:
        what: mounthole
        params:
          diameter: sd
        where:
          ref: mirror_thumbs_gamma_cluster
          shift: [0.75kx, -0.25ky]

      mount_hole_pinky_mirror:
        what: mounthole
        params:
          diameter: sd
        where:
          ref: mirror_matrix_pinky_top
          shift: [0.25kx, 0.75ky]

      mount_hole_middle_mirror:
        what: mounthole
        params:
          diameter: sd
        where:
          ref: mirror_matrix_middle_bottom
          shift: [-0.25kx, -0.75ky]

      # Name
      project_name:
        what: text
        where:
          ref.aggregate.parts: [matrix_index_top, mirror_matrix_index_top]
          shift: [-7, -44]
        params:
          layer: F.SilkS
          text: "crabapplepad v2.0"
          justify: left

      project_author:
        what: text
        where:
          ref.aggregate.parts: [matrix_index_top, mirror_matrix_index_top]
          shift: [-7.3, -46]
        params:
          layer: F.SilkS
          text: "by @kumekay 2024"
          justify: left

      jlcpcd_order_id:
        what: text
        where:
          ref.aggregate.parts: [matrix_index_top, mirror_matrix_index_top]
          shift: [-5, -60]
        params:
          text: "JLCJLCJLCJLC"
          justify: left
